version: '3.8'

# TODO: Run this command to initially get a certificate: IMPORTANT: Change the email and domain to your own
# docker run -it --rm -p 80:80 --name certbot-standalone -v ./nginx/certbot/conf:/etc/letsencrypt certbot/certbot certonly --standalone --preferred-challenges http --agree-tos --no-eff-email --email test@example.com -d example.com

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    environment:
      - N8N_PORT=5678
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      # TODO: Change this password to a strong one
      - N8N_BASIC_AUTH_PASSWORD=XXXXXXXXX
      # TODO: Change this to your own domain
      - N8N_HOST=example.com
      # TODO: Change this to your own domain
      - WEBHOOK_URL=https://example.com/
    volumes:
      - /mnt/n8n-volume:/home/node/.n8n
    networks:
      - app-network

  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    volumes:
      - ./nginx/n8n.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - n8n
    networks:
      - app-network

  certbot:
    container_name: certbot
    image: certbot/certbot  
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    # Add a cron job for automatic renewal
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot --webroot-path=/var/www/certbot --quiet && echo 'Certificate renewed'; sleep 24h; done"

networks:
  app-network:
    driver: bridge
